#Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    view:
        formats: { json: true, xml: false, rss: false }
        view_response_listener: true
    body_converter:
        enabled: true
    serializer:
        serialize_null: true
    format_listener:
        rules:
            - { path: ^/api, fallback_format: json, priorities: [ 'json' ] }
            - { path: '^/', priorities: [ 'html', '*/*' ], fallback_format: ~, prefer_extension: true }
